pub usingnamespace @cImport({
    @cDefine("WOLFSSL_TLS13", "");
    @cDefine("SESSION_INDEX", "");
    @cDefine("SESSION_CERTS", "");

    @cDefine("WOLFSSL_HAVE_ATOMIC_H", "");
    @cDefine("HAVE_C___ATOMIC", "1");
    @cDefine("HAVE_THREAD_LS", "");
    @cDefine("NO_DO178", "");
    // this should be arch specific
    @cDefine("WOLFSSL_X86_64_BUILD", "");

    @cDefine("ERROR_QUEUE_PER_THREAD", "");
    @cDefine("TFM_TIMING_RESISTANT", "");
    @cDefine("ECC_TIMING_RESISTANT", "");
    @cDefine("WC_RSA_BLINDING", "");
    @cDefine("WOLFSSL_USE_ALIGN", "");
    @cDefine("WOLFSSL_SHA224", "");
    @cDefine("WOLFSSL_SHA512", "");
    @cDefine("WOLFSSL_SHA384", "");
    @cDefine("HAVE_HKDF", "");
    @cDefine("NO_DSA", "");
    @cDefine("HAVE_ECC", "");
    @cDefine("TFM_ECC256", "");
    @cDefine("ECC_SHAMIR", "");
    @cDefine("WC_RSA_PSS", "");
    @cDefine("WOLFSSL_PSS_LONG_SALT", "");
    @cDefine("WOLFSSL_ASN_TEMPLATE", "");
    @cDefine("WOLFSSL_ASN_PRINT", "");
    @cDefine("WOLFSSL_BASE64_ENCODE", "");
    @cDefine("WOLFSSL_SHA3", "");
    @cDefine("WOLFSSL_NO_SHAKE128", "");
    @cDefine("WOLFSSL_NO_SHAKE256", "");
    @cDefine("HAVE_POLY1305", "");
    @cDefine("HAVE_CHACHA", "");
    @cDefine("HAVE_HASHDRBG", "");
    @cDefine("NO_INLINE", "");
    @cDefine("HAVE_TLS_EXTENSIONS", "");
    @cDefine("HAVE_SNI", "");
    @cDefine("HAVE_TLS_EXTENSIONS", "");
    @cDefine("HAVE_SUPPORTED_CURVES", "");
    @cDefine("HAVE_FFDHE_2048", "");
    @cDefine("HAVE_SUPPORTED_CURVES", "");
    @cDefine("HAVE_TLS_EXTENSIONS", "");
    @cDefine("HAVE_EXTENDED_MASTER", "");
    @cDefine("HAVE_TLS_EXTENSIONS", "");
    @cDefine("HAVE_SNI", "");
    @cDefine("HAVE_MAX_FRAGMENT", "");
    @cDefine("HAVE_TRUNCATED_HMAC", "");
    @cDefine("HAVE_ALPN", "");
    @cDefine("HAVE_TRUSTED_CA", "");
    @cDefine("HAVE_SUPPORTED_CURVES", "");
    @cDefine("NO_RC4", "");
    @cDefine("HAVE_ENCRYPT_THEN_MAC", "");
    @cDefine("NO_PSK", "");
    @cDefine("NO_MD4", "");
    @cDefine("WOLFSSL_SP_MATH_ALL", "");
    @cDefine("WOLFSSL_SP_X86_64", "");
    @cDefine("WC_NO_ASYNC_THREADING", "");
    @cDefine("HAVE_DH_DEFAULT_PARAMS", "");
    @cDefine("WOLFSSL_SYS_CA_CERTS", "");
    @cDefine("NO_DES3", "");
    @cDefine("GCM_TABLE_4BIT", "");
    @cDefine("HAVE_AESGCM", "");
    @cDefine("HAVE_TLS_EXTENSIONS", "");
    @cDefine("HAVE_SERVER_RENEGOTIATION_INFO", "");
    @cDefine("HAVE___UINT128_T 1", "");
    @cDefine("HAVE_WC_INTROSPECTION", "");

    @cInclude("wolfssl/ssl.h");
});
